### ISSUE TITLE
🆙 QP800 ingress errors when deploying 4.1.0 Allure TestOps

### ISSUE THREAD

**Issue by cheshi-mantu** [qameta/allure-testops-deployment#10]
<div> Freshdesk Ticket ID: <a href="https://newaccount1641218771113.freshdesk.com/a/tickets/726">726</a></div>
                       <div> Freshdesk Ticket Agent: George I.</div>
                       <div> Freshdesk Ticket Agent Email: egor.ivanov@qameta.io</div>
                       <div> Ticket Priority: Medium</div>
                       <div> Freshdesk Ticket Description: </div><div>При деплое 4.1.0 в k8 возникает ошибка helm-chart

Error: template: allure-testops/templates/network/ingress.yaml:35:20: executing "allure-testops/templates/network/ingress.yaml" at &lt;.Values.host&gt;: host is not a method but has arguments
с таким values.yaml
version: 4.1.0
host: test.qwe.qwe
network:
  ingress:
    enabled: true
    className:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls:
    enabled: true
    secretName: secretname

темплейт ингресса:
  tls:
    - secretName: {{ .Values.network.tls.secretName }}
      hosts:
        - {{ .Values.host . }}

ругается на 
 - {{ .Values.host . }}</div>

**Comment by cheshi-mantu** [comment]
<div>Agent George I. linked Freshdesk ticket <a href="https://newaccount1641218771113.freshdesk.com/a/tickets/726">726</a> for this issue.</div><br/>

**Comment by andrey-ryoo** [comment]
Resolved
