### ISSUE TITLE
to support all IAMs available in old helm chart

### ISSUE THREAD

**Issue by cheshi-mantu** [qameta/allure-testops-deployment#11]
<div> Freshdesk Ticket ID: <a href="https://newaccount1641218771113.freshdesk.com/a/tickets/727">727</a></div>
                       <div> Freshdesk Ticket Agent: George I.</div>
                       <div> Freshdesk Ticket Agent Email: egor.ivanov@qameta.io</div>
                       <div> Ticket Priority: Low</div>
                       <div> Freshdesk Ticket Description: </div><div>Сейчас нет поддержки настройки sso через helm для релиза 4.1.0. Было бы хорошо поддержать, так как раньше эта возможность была.

По мотивам проблемы из чата <a href="https://t.me/allure_ru/26966" rel="noreferrer">https://t.me/allure_ru/26966</a></div>

need to support all IAM providers listed here: https://docs.qameta.io/allure-testops/getstarted/auth/main/

**Comment by cheshi-mantu** [comment]
<div>Agent George I. linked Freshdesk ticket <a href="https://newaccount1641218771113.freshdesk.com/a/tickets/727">727</a> for this issue.</div><br/>

**Comment by andrey-ryoo** [comment]
All done
