### ISSUE TITLE
helm chart PG operator integration

### ISSUE THREAD

**Issue by cheshi-mantu** [qameta/allure-testops-deployment#15]
<div> Freshdesk Ticket ID: <a href="https://newaccount1641218771113.freshdesk.com/a/tickets/892">892</a></div>
                       <div> Freshdesk Ticket Agent: George I.</div>
                       <div> Freshdesk Ticket Agent Email: egor.ivanov@qameta.io</div>
                       <div> Ticket Priority: Low</div>
                       <div> Freshdesk Ticket Description: </div><div dir="ltr"><div>Hi. <br><br>We use postgres operator which creates a database and puts a secret from it in the k8s secret. It would be nice to be able to use this secret directly. <br><br>Now we have to get the password from this secret in advance and write in values.yaml.<br><br>This possibility would be desirable for all external systems of type redis/rabbit/postgres<br>
</div></div>

**Comment by cheshi-mantu** [comment]
<div>Agent George I. linked Freshdesk ticket <a href="https://newaccount1641218771113.freshdesk.com/a/tickets/892">892</a> for this issue.</div><br/>

**Comment by cheshi-mantu** [comment]
@andrey-ryoo @a-ryoo 
sirs, any comments here?

**Comment by a-ryoo** [comment]
Will be resolved in https://github.com/qameta/allure-testops-deployment/issues/40

**Comment by Frodox** [comment]
may be, someday in https://github.com/qameta/infra/issues/659
