### ISSUE TITLE
external rabbitmq port to helm chart

### ISSUE THREAD

**Issue by EtnDiaz** [qameta/allure-testops-deployment#16]
Hello, Please add the ability to specify a different port for rabbit-mq in helm cart.🙏

**Comment by cheshi-mantu** [comment]
@EtnDiaz 
Hello sir!
please file a feature request via https://help.qameta.io using the email address of the company having the Allure TestOps licence.
thanks!

**Comment by andrey-ryoo** [comment]
Thanks for reporting
