### ISSUE TITLE
👎 certificate is now bound to app name

### ISSUE THREAD

**Issue by cheshi-mantu** [qameta/allure-testops-deployment#2]
ingress.yaml, TLS certificate name: 
we use same wildcard certificate everywhere, right now cert name is bound to App name. Need to have something like ingress.tls.certName and be able to override with it (app name can be default if custom cert name is not specified).

**Comment by andrey-ryoo** [comment]
https://github.com/qameta/allure-testops-deployment/blob/master/charts/allure-testops/templates/network/ingress.yaml
Done

**Comment by andrey-ryoo** [comment]
Certificate secretName can be specified in .Values.tls.secretName
