### ISSUE TITLE
Istio annotations support

### ISSUE THREAD

**Issue by cheshi-mantu** [qameta/allure-testops-deployment#20]
<div> Freshdesk Ticket ID: <a href="https://newaccount1641218771113.freshdesk.com/a/tickets/1155">1155</a></div>
                       <div> Freshdesk Ticket Agent: George I.</div>
                       <div> Freshdesk Ticket Agent Email: egor.ivanov@qameta.io</div>
                       <div> Ticket Priority: Medium</div>
                       <div> Freshdesk Ticket Description: </div><div style="font-family:-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, sans-serif; font-size:14px"><div dir="ltr"><div>Hello,&nbsp;</div><div dir="ltr">I'd like to reopen a support ticket issued in the jira.qameta.io: <a href="https://jira.qameta.io/servicedesk/customer/portal/1/AES-1614" rel="noreferrer" target="">AES-1614</a></div><div dir="ltr">Please let me know if any further information is required from my side.</div><div style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;  text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 10px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif">As I mentioned in the previous message, we use istio-ingress in our setup. To enable this for Allure TestOps, we should</div><ul style="box-sizing: border-box; margin-top: 10px; margin-bottom: 10px; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;  text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif" type="square"><li style="box-sizing: border-box">label the namespace with the following (done on our side)<pre style="box-sizing: border-box; overflow: auto; font-family: monospace, monospace; font-size: 1em; display: block; background-color: rgb(235, 237, 240); padding: 0px; cursor: pointer; min-height: 31px; margin: 0px; white-space: pre-wrap; overflow-wrap: break-word"><code style="box-sizing: border-box; font-family: SFMono-Medium, &quot;SF Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Roboto Mono&quot;, &quot;Ubuntu Mono&quot;, Menlo, Courier, monospace; font-size: 1em">
  labels:
    istio-injection: enabled
</code></pre></li><li style="box-sizing: border-box">update allure-testops workloads annotations (not svcs annotations) for pods that do not require istio-injection<pre style="box-sizing: border-box; overflow: auto; font-family: monospace, monospace; font-size: 1em; display: block; background-color: rgb(235, 237, 240); padding: 0px; cursor: pointer; min-height: 31px; margin: 0px; white-space: pre-wrap; overflow-wrap: break-word"><code style="box-sizing: border-box; font-family: SFMono-Medium, &quot;SF Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Roboto Mono&quot;, &quot;Ubuntu Mono&quot;, Menlo, Courier, monospace; font-size: 1em">
    annotations:
      sidecar.istio.io/inject: "false"
</code></pre><div style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; margin-top: 10px; padding: 0px">This could be done while populating the following</div><pre style="box-sizing: border-box; overflow: auto; font-family: monospace, monospace; font-size: 1em; display: block; background-color: rgb(235, 237, 240); padding: 0px; cursor: pointer; min-height: 31px; margin: 10px 0px 0px; white-space: pre-wrap; overflow-wrap: break-word"><code style="box-sizing: border-box; font-family: SFMono-Medium, &quot;SF Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Roboto Mono&quot;, &quot;Ubuntu Mono&quot;, Menlo, Courier, monospace; font-size: 1em">
spec.template.metadata.annotations
</code></pre></li></ul><div style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;  text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 10px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif">We have already managed to populate this value for redis, postgresql, and rabbitmq pods because they have this `spec.template.metadata.annotations` value parametrized in their helm templates (in a statefulset).<br style="box-sizing: border-box">For instance, for <a href="https://github.com/helm/charts/blob/master/stable/redis/templates/redis-slave-statefulset.yaml" rel="noreferrer" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 82, 204); text-decoration: none; word-break: break-word; overflow-wrap: break-word" target="_blank">redis-slave</a> this could be done via `.Values.slave.podAnnotations` value in the config.yaml. (See the picture attached).</div><pre style="box-sizing: border-box; overflow: auto; font-family: monospace, monospace; font-size: 14px; display: block; background-color: rgb(235, 237, 240); padding: 0px; cursor: pointer; min-height: 31px; margin: 10px 0px 5px; white-space: pre-wrap; overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(23, 43, 77)"><code style="box-sizing: border-box; font-family: SFMono-Medium, &quot;SF Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Roboto Mono&quot;, &quot;Ubuntu Mono&quot;, Menlo, Courier, monospace; font-size: 1em">
redis:
  master:
    podAnnotations:
      sidecar.istio.io/inject: "false"
  slave:
    podAnnotations:
      sidecar.istio.io/inject: "false"
</code></pre><div style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;  text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 10px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif">However, Allure's helm templates (deployments) don't have this option parametrized from the values.yaml, e.g. the <a href="https://github.com/qameta/helm-charts/blob/master/charts/allure-ee/templates/report-dep.yaml" rel="noreferrer" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 82, 204); text-decoration: none; word-break: break-word; overflow-wrap: break-word" target="_blank">report</a> as an example.</div><div style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; color: rgb(24, 50, 71); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;  text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial">&nbsp;</div><div style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;  text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 10px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif">Hence, we would greatly appreciate it if you could similarly update your default helm template.</div><div style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;  text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 10px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif"><br style="box-sizing: border-box"></div><div dir="ltr" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;  text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 10px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif">Unfortunately, the current Allure helm template&nbsp;(<a href="https://github.com/qameta/allure-testops-deployment" rel="noreferrer" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 101, 255); text-decoration: none; word-break: break-word; overflow-wrap: break-word" target="_blank">https://github.com/qameta/allure-testops-deployment</a>)&nbsp;doesn't allow parametrizing<b style="box-sizing: border-box; font-weight: 700"><u style="box-sizing: border-box">&nbsp;pod annotations</u></b> in a values.yaml. Hence, I'd like to reopen an issue to check whether it's possible for you to update a&nbsp;<b style="box-sizing: border-box; font-weight: 700"><u style="box-sizing: border-box">deployment template</u></b>, not a service one.</div></div></div>

**Comment by andrey-ryoo** [comment]
Done
