### ISSUE TITLE
🆕 to supply external secret name to be used in the chart

### ISSUE THREAD

**Issue by cheshi-mantu** [qameta/allure-testops-deployment#3]
AlphaSense - task 2

Current version assumes that it’s a safe way to pass secret data in values.yaml, and then create infra/secret.yaml. For us this way is not an option, and our secret is synced from Vault via ExternalSecret object. Can we have an option in values.yaml to skip secret.yaml creation and optionally supply an external secret name?

**Comment by sole0bserver** [comment]
I think it was covered [in this PR](https://github.com/qameta/allure-testops-deployment/pull/6), so we can close this one.
