### ISSUE TITLE
Report maxS3Concurrency/ALLURE_BLOBSTORAGE_MAXCONCURRENCY, should be string not integer

### ISSUE THREAD

**Issue by allanian** [qameta/allure-testops-deployment#32]
Hello, can you help us with that issue,
we're installed allure with argocd on kubernetes 1.25.6
in values.yaml we are set this for report:
```
        report:
          replicaCount: 2
          maxS3Concurrency: '200'
```
but we're get issue 
StatefulSet in version "v1" cannot be handled as a StatefulSet: json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string

in statefulset envs coming like this:
```
            - name: ALLURE_BLOBSTORAGE_MAXCONCURRENCY
              value: 200
```

**Comment by cheshi-mantu** [comment]
@allanian Hi,
thanks for reporting this
let me communicate with the developer

**Comment by cheshi-mantu** [comment]
@allanian the issue has been fixed, please wait 1-2 hours for the new release of the helm chart

**Comment by cheshi-mantu** [comment]
@allanian updated helm chart is now acailable

**Comment by allanian** [comment]
nice, its working!
