### ISSUE TITLE
🆕 need to pass OKTA deployment envs to gateway service env

### ISSUE THREAD

**Issue by cheshi-mantu** [qameta/allure-testops-deployment#4]
Okta authentication: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_* environment variables are not passed to Gateway deployment. Need to have those passed. Doc: https://docs.qameta.io/allure-testops/getstarted/auth/openid-okta/#deployment-in-kubernetes-1

**Comment by andrey-ryoo** [comment]
Done
