### ISSUE TITLE
JAVA_TOOL_OPTIONS - MinHeapFreeRatio / MaxHeapFreeRatio

### ISSUE THREAD

**Issue by mustdiechik** [qameta/allure-testops-deployment#48]
https://github.com/qameta/allure-testops-deployment/blob/d8abdfb2ced442a99cbd8823d6f13ab5f166d251/charts/allure-testops/templates/_helpers.tpl#L268

Is mistake there in double MinHeapFreeRatio declaration ?

I think, it should be "-XX:MaxHeapFreeRatio=70"

**Comment by a-ryoo** [comment]
Hi, good point, but we have better optimization settings tested already. There are minor issues with them, so as soon we done with them the mechanism will change

**Comment by alexey-bogdanov** [comment]
Fixed
