### ISSUE TITLE
no storageClass internal postgresql rabbitmq redis-data-allure-testops-redis-master-0

### ISSUE THREAD

**Issue by vvp1983** [qameta/allure-testops-deployment#52]
Helm no storageClass - so no persistent volumes available for this claim and no storage class is set. Need like storageClass for internal mino.

**Comment by a-ryoo** [comment]
Please take a look at https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

Our chart provides rabbit, redis and other services as dependencies. You can lookup values from original charts and override them

**Comment by cheshi-mantu** [comment]
won't be implemented on our chart side
