### ISSUE TITLE
Image allure/allure-report removed from docker.io

### ISSUE THREAD

**Issue by chapsuk** [qameta/allure-testops-deployment#54]
Cant pull image from docker.io
```
docker pull docker.io/allure/allure-report:4.14.0
Error response from daemon: pull access denied for allure/allure-report, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Looks like repo was removed from docker.io
https://hub.docker.com/u/allure

**Comment by cheshi-mantu** [comment]
hi there
` may require 'docker login': denied: requested access to the resource is denied`
this is all true.
you need to be authenticated and authorised to pull images

**Comment by chapsuk** [comment]
Please, check the image on docker.id, it was removed

**Comment by chapsuk** [comment]
@cheshi-mantu you mean `docker.io/allure/allure-report` image is private now?

**Comment by cheshi-mantu** [comment]
Allure Testops registry was always private. It's commercial product, you can't access the registry without communicating to the sales and having either commercial or trial licence, sir.

**Comment by cheshi-mantu** [comment]
the image you are referring to is still there
<img width="310" alt="image" src="https://github.com/qameta/allure-testops-deployment/assets/8607348/95f4d376-f45e-4a8b-954a-a5e5ad6b3048">

**Comment by chapsuk** [comment]
very strange, we are deploy it 3 month ago without any additional docker credentials, on last cluster upgrade we got the image pull error. 
Thanks! trying to contact with sales then
