### ISSUE TITLE
🆙 to update helm chart to support saml as per the existing documentaiton

### ISSUE THREAD

**Issue by cheshi-mantu** [qameta/allure-testops-deployment#7]
we've following described available integations with external IAM systems
https://docs.qameta.io/allure-testops/getstarted/auth/main/
current version of the helm chart does not allow to set-up the integration with SAML which ise required and used by some clients and this will break their integratiion in case they migrate to the new Helm chart

we need to implement all described options
![image](https://user-images.githubusercontent.com/8607348/172885892-c618467e-4728-4d7c-931c-be827028a2cc.png)

**Comment by andrey-ryoo** [comment]
Now works, thanks for inconvenience
